vich_uploader:
    db_driver: orm

    mappings:
        chemin_image_profil:
            uri_prefix: '%image_profil%'
            upload_destination: '%kernel.project_dir%/public%image_profil%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
