vich_uploader:
    db_driver: orm

    mappings:
        image_profil:
            uri_prefix: '%image_profil%'
            upload_destination: '%kernel.project_dir%/public%image_profil%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update : false

